name: circle
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

# dependencies مرتبة أبجدياً
dependencies:
  cached_network_image: ^3.4.1
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  easy_localization: ^3.0.2
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.7.0
  get_it: ^8.0.0
  go_router: ^14.2.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  pin_code_fields: ^8.0.1
  pin_code_text_field: ^1.8.0
  retrofit: ^4.4.1

# dev_dependencies مرتبة أبجدياً
dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  retrofit_generator: ^9.1.2

flutter:
  uses-material-design: true

  # Assets section
  assets:
    - assets/images/

  # Fonts section
  fonts:
    - family: MadaniArabic
      fonts:
        - asset: fonts/alfont_com_Madani-Arabic-Regular.ttf
