// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLSxZ0c4aQO3dkMe4NTtOPTyTKOPTAnCw',
    appId: '1:886715113572:web:f4c1e1338e5be5d41e3f71',
    messagingSenderId: '886715113572',
    projectId: 'circle-app-d5211',
    authDomain: 'circle-app-d5211.firebaseapp.com',
    storageBucket: 'circle-app-d5211.appspot.com',
    measurementId: 'G-439HWH88DR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCw7nKzingBrJgXG4XCbiZj5ld2Wer5bM',
    appId: '1:886715113572:android:03b42ff3b03787d51e3f71',
    messagingSenderId: '886715113572',
    projectId: 'circle-app-d5211',
    storageBucket: 'circle-app-d5211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5ue6hQ7beqrMWpEMgCQEigmfwyfvyWSg',
    appId: '1:886715113572:ios:bccd69cee81aa5f61e3f71',
    messagingSenderId: '886715113572',
    projectId: 'circle-app-d5211',
    storageBucket: 'circle-app-d5211.appspot.com',
    iosBundleId: 'com.example.circle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5ue6hQ7beqrMWpEMgCQEigmfwyfvyWSg',
    appId: '1:886715113572:ios:bccd69cee81aa5f61e3f71',
    messagingSenderId: '886715113572',
    projectId: 'circle-app-d5211',
    storageBucket: 'circle-app-d5211.appspot.com',
    iosBundleId: 'com.example.circle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLSxZ0c4aQO3dkMe4NTtOPTyTKOPTAnCw',
    appId: '1:886715113572:web:4234932079f094b01e3f71',
    messagingSenderId: '886715113572',
    projectId: 'circle-app-d5211',
    authDomain: 'circle-app-d5211.firebaseapp.com',
    storageBucket: 'circle-app-d5211.appspot.com',
    measurementId: 'G-DWPL5K9N9K',
  );
}
